### ISSUE TITLE
Initialize singleton components on system registration

### ISSUE THREAD

**Issue by fernandojsg** [fernandojsg/ecsy#22]
Many times we need to store data related to systems internally, a good practice to avoid storing data on the systems could be to use singleton components and add some syntactic sugar for that:

If we create a system in this way:
```javascript
world.registerSystem(SystemA, {valueA: 1, valueB: 2});
```

it will create a singleton component named `systemA` (As if we had previously created a `SystemA` component with `valueA` and `valueB` attributes).
And we could access the component from within the system by referencing `this.component`:
```javascript
execute() {
    this.component.valueA += 2;
}
```

**Comment by joshmarinacci** [comment]
Since you removed singletons should this be closed?

**Comment by fernandojsg** [comment]
Yes, I'll just close it by now and reopen if we feel we want to add it as syntactic sugar
