### ISSUE TITLE
Implement filters on queries

### ISSUE THREAD

**Issue by fernandojsg** [fernandojsg/ecsy#31]
Allow users to define a filter for the queries could be useful to filter by component's' values easily.
The drawback of this is that filter will create a new instance of the array, and the events (`onComponentAdded`, `onComponentChanged`,...) should also be modified by the filter

```javascript
class SystemB extends System {
  init() {
    return {
      queries: {
        entities: {
          components: [FooComponent],
          filter: entity => entity.getComponent(FooComponent).value > 2
        }
      }
    };
  }
  execute() {}
}
```

**Comment by joshmarinacci** [comment]
Can't you do this anyway when you grab the component list from the query?

**Comment by fernandojsg** [comment]
@joshmarinacci yep, probably that makes more sense. I guess it won't be that commonly used as to move it to the core, and you could always do the filter yourself as you mentioned and we avoid dealing with the allocation of a new array.
Closing by now
