### ISSUE TITLE
Move queries to System static property

### ISSUE THREAD

**Issue by robertlong** [fernandojsg/ecsy#48]
I'd like to propose moving the `queries` object from the return value of the `init()` function to a `static queries` property on the `System` class. This change will make it possible to know what dependencies a system has before it is instantiated which is important for writing system schedulers.

Ex.

```js
class MySystem extends System {
  static queries = {
    foo: { components: [ComponentA, ComponentB] }
    bar: { components: [ComponentB, ComponentC] }
  };
  init() {}
  execute() {}
}
```

Or without static property support (currently unsupported without babel / typescript)

```js
class MySystem extends System {
  init() {}
  execute() {}
}

MySystem.queries = {
  foo: { components: [ComponentA, ComponentB] }
  bar: { components: [ComponentB, ComponentC] }
};
```

This proposal is similar to the syntax of React's [`propTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes) or [`defaultProps`](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values).

An alternate proposal could be introducing a `static query()` method which returns the queries for the system.

Ex.

```js
class MySystem extends System {
  static query() {
    return {
      foo: { components: [ComponentA, ComponentB] }
      bar: { components: [ComponentB, ComponentC] }
    };
  }
  init() {}
  execute() {}
}
```

I think this should be avoided since the `queries` object should not change and could be referenced multiple times in the scheduler which would allocate additional objects unnecessarily. One benefit is that static class methods are currently supported in evergreen browsers without transpilation. However, React has made the decision to go forward with this syntax for `propTypes` and `defaultProps` and I think we should as well.

One more proposal would be to do nothing to the syntax other than change examples to set queries in the constructor or with a class property:

Ex.
```js
class MySystem extends System {
  constructor(world) {
    super(world);

    this.queries = {
      foo: { components: [ComponentA, ComponentB] }
      bar: { components: [ComponentB, ComponentC] }
    };
  }
  init() {}
  execute() {}
}
```

Class properties have better support in current browsers. See the [Class Fields Proposal](https://github.com/tc39/proposal-class-fields#implementations).

```js
class MySystem extends System {
  queries = {
    return {
      foo: { components: [ComponentA, ComponentB] }
      bar: { components: [ComponentB, ComponentC] }
    };
  }
  init() {}
  execute() {}
}
```

A scheduler would then be assumed to operate after a system has been registered with the `World` (which calls the system's constructor). Custom schedulers could then be implemented by subclassing `SystemManager` and providing a custom `SystemManager` when constructing the `World`.

**Comment by joshmarinacci** [comment]
I also vote for a static field. This reinforces the idea that it's something which you shouldn't change and is the same for every class

**Comment by joshmarinacci** [comment]
Could we decide this by the v0 milestone?

**Comment by fernandojsg** [comment]
Closed by https://github.com/fernandojsg/ecsy/pull/73
