### ISSUE TITLE
Rename `createComponent` to prevent conflict with `world.createComponent`

### ISSUE THREAD

**Issue by robertlong** [fernandojsg/ecsy#76]
@fernandojsg shared a proposal for `world.createComponent()` which returns an instance of a component created by a `ComponentManager`. We should probably rename the top level `createComponent` function to something else to prevent that conflict.

Some ideas:
```
createComponentClass()
defineComponent()
```

**Comment by fernandojsg** [comment]
Thanks!, Changed to `createComponentClass`. Closing it now, open to suggestions in the future if we find it confusing.
